server:
  # 端口
  port: 8080
spring:
  application:
    # 服务名
    name: security
  thymeleaf:
    # 静态文件的地址
    prefix: classpath:/static/
    # 必须是。html 否则无法是被解析逻辑
    suffix: .html
    # 文件模式html
    mode: HTML
#  # 数据源配置注意数据库的名字
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/private_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: root
#    password: 123456

# mybatisPlus配置 暂时先不用
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # mapper bean的位置
  type-aliases-package: com.example.demo.bean
  # 输出sql日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl











